# environment variables.
@Host_LOCAL = http://localhost:5000

GET {{Host_LOCAL}}/payout/setBalanceTransferPermission


# with input body
###
POST  {{Host_LOCAL}}/support/testMultipart
Content-Type: application/json

{
    "name": "John Doe",
    "email": "raju@gmail.com",
    "subject": "Test",
    "message": "Test message"
}

# with api token
###
GET  http://api.umediad.com/support/getSupports
x-auth-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk5YzE2YzIyNzk3YTVkZDg0ZTIzMjMiLCJ1c2VyRW1haWwiOiJyYWp1NDBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyYWp1NDAiLCJmdWxsTmFtZSI6Ik1pamFudXIgUmFobWFuIiwicm9sZSI6InNlbGxlciIsImlzUHJvZmlsZU9rIjp0cnVlLCJpc1NlbGxlciI6ZmFsc2UsImlzX3N1YnNjcmliZWQiOmZhbHNlLCJpYXQiOjE2Mzc2NDE4MDksImV4cCI6MTYzNzcyODIwOX0.RqiVsbmVngE5YxahuoZLbzR9R-zSVTSiK8m7MOSqmfY

# with api token and input body
###
POST  http://api.umediad.com/support/addSupport
x-auth-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk5YzE2YzIyNzk3YTVkZDg0ZTIzMjMiLCJ1c2VyRW1haWwiOiJyYWp1NDBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyYWp1NDAiLCJmdWxsTmFtZSI6Ik1pamFudXIgUmFobWFuIiwicm9sZSI6InNlbGxlciIsImlzUHJvZmlsZU9rIjp0cnVlLCJpc1NlbGxlciI6ZmFsc2UsImlzX3N1YnNjcmliZWQiOmZhbHNlLCJpYXQiOjE2Mzc2NDE4MDksImV4cCI6MTYzNzcyODIwOX0.RqiVsbmVngE5YxahuoZLbzR9R-zSVTSiK8m7MOSqmfY
Content-Type: application/json

{
    "name": "John Doe",
    "email": "raju@gmail.com",
    "subject": "Test",
    "message": "Test message"
}

